# Generated by Django 5.1 on 2024-08-12 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_link', models.URLField()),
                ('nano_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='NanoLink',
        ),
    ]
